name: CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: yarn install

      - name: Configure actions username
        run:
          git config --global user.name 'GitHub Actions'

      - name: Configure actions email
        run: 
          git config --global user.email 'actions@users.noreply.github.com'

      - name: Checkout to gh-pages
        run:
          git checkout --orphan gh-pages

      - name: Checking Dirs
        run:
          ls

      - name: Build aplication
        run: yarn build

      - name: Moving Files
        run:
          mv output/* .

      - name: Adding output files
        run: 
          git add --all

      - name: Commiting output directory
        run:
          git commit -m "Deploying to GitHub Pages"
          
      - name: Pushing to Github Pages
        run:
          git push origin HEAD:gh-pages --force